Repository FRONTENDSCHOOL8/super-market, pull requests merged in 2024-01, with the labels that each got.

#7 feat(feat/sang/#4): 헤더 마크업 및 스타일링, asset 추가
  public/icon_down.webp
  public/images/menu/Baby.svg
  public/images/menu/Bread.svg
  public/images/menu/Coffee.svg
  public/images/menu/Cook.svg
  public/images/menu/Cosmetics.svg
  public/images/menu/Detergent.svg
  public/images/menu/Dog.svg
  public/images/menu/Food.svg
  public/images/menu/Fruit.svg
  public/images/menu/HomeAppliances.svg
  public/images/menu/Meat.svg
  public/images/menu/Oil.svg
  public/images/menu/Salad.svg
  public/images/menu/SeaFood.svg
  public/images/menu/Snack.svg
  public/images/menu/Traditional Liquor.svg
  public/images/menu/Travel.svg
  public/images/menu/Vegetable.svg
  public/images/menu/Wine.svg
  public/images/menu/burger.svg
  public/images/menu/gift.svg
  public/images/menu/medicine.svg
  public/images/menu/menulink-Icon-hover.svg
  public/images/menu/menulink-Icon.svg
  public/images/menu/shampoo.svg
  public/images/search/cancel.svg
  public/images/search/search.svg
  public/logo.svg
  src/assets/new.svg
  src/pages/products/index.html
  src/styles/layout/_header.scss
Labels: Feature

#9 feat(feat/ryu/#1): 메인 페이지 마크업 및 스타일링
  index.html
  public/images/menu/arrow.svg
  public/images/menu/banner-arrow.svg
  public/images/menu/cart.svg
  src/assets/main/banner01.png
  src/assets/main/banner02.png
  src/assets/main/banner03.png
  src/assets/main/banner04.png
  src/assets/main/line-banner.png
  src/assets/main/popup.png
  src/assets/main/product01.png
  src/assets/main/product02.png
  src/assets/main/product03.png
  src/assets/main/product04.png
  src/styles/components/_index.scss
  src/styles/components/_productCard.scss
  src/styles/components/_recentBar.scss
  src/styles/pages/_index.scss
  src/styles/pages/_main.scss
Labels: Feature

#11 feat(feat/sang/#8): 푸터 마크업 및 이미지 추가
  public/images/family/isms.png
  public/images/family/privacy.png
  public/images/family/tosspayments.png
  public/images/family/wooribank.png
  public/images/sns/blog.png
  public/images/sns/facebook.png
  public/images/sns/instagram.png
  public/images/sns/post.png
  public/images/sns/youtube.png
  src/pages/products/index.html
  src/styles/layout/_footer.scss
Labels: Feature

#13 Feat/sang/#12: 네비게이션 메뉴 마크업 및 스타일링
  public/images/checkbox/roundcheck.png
  public/images/checkbox/rounduncheck.png
  public/images/menu/downarrow.svg
  public/images/menu/help.svg
  public/images/pagination/firstpage.svg
  public/images/pagination/lastpage.svg
  public/images/pagination/next.svg
  public/images/pagination/prev.svg
  src/pages/products/index.html
  src/styles/layout/_footer.scss
  src/styles/pages/_products.scss
Labels: Feature

#14 feat(feat/ryu/#10): 장바구니 페이지 마크업 및 스타일링
  public/images/menu/close.svg
  public/images/menu/map.svg
  public/images/menu/type-frozen.svg
  public/images/menu/type-normal.svg
  public/images/menu/type-refrigerated.svg
  src/pages/cart/index.html
  src/styles/pages/_cart.scss
Labels: Feature

#17 modify(feat/sang/#8): 푸터 border-top 수정 적용, 일부 속성 Sass 믹스인으로 수정 적용
  src/styles/layout/_footer.scss
Labels: Feature

#20 Feat/ryu/#18: 메인 페이지 배너 스와이퍼 완성
  index.html
  main.js
  package-lock.json
  package.json
  src/styles/pages/_main.scss
Labels: Feature

#21 feat(feat/sang/#19): 화면 스크롤 시 상단에 메뉴 고정하도록 기능 추가
  src/lib/components/header.js
  src/lib/components/index.js
  src/lib/index.js
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/layout/_header.scss
Labels: Feature

#23 Feat/kim/#6: 회원가입 페이지 마크업 및 디자인 완료
  public/images/checkbox/radiochecked.png
  public/images/checkbox/radiouncheck.png
  public/images/menu/arrow_unfill.svg
  src/pages/register/index.html
  src/pages/register/register.js
  src/styles/pages/_register.scss
Labels: Feature

#24 bugfix(feat/sang/#22): 불필요한 코드 및 주석 제거
  src/lib/utils/delay.js
Labels: BugFix

#30 Modifiy(feat/ryu/#28): 장바구니 페이지 수정
  src/pages/cart/index.html
  src/styles/pages/_cart.scss
Labels: Help

#31 feat(feat/kina/#3): 상품디테일,후기,문의게시판 마크업 스타일링 완료
  public/images/product/Heart-disabled.svg
  public/images/product/Heart.svg
  public/images/product/bell.svg
  public/images/product/next.svg
  public/images/product/prev.svg
  public/images/product/product01-description.png
  public/images/product/product01-detail.png
  public/images/product/product01.png
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature

#33 feat(feat/kim/#25): 로그인 페이지 html/css 일부 수정 및 자바스크립트 파일 생성
  src/pages/login/index.html
  src/pages/login/login.js
  src/styles/pages/_login.scss
Labels: Feature

#35 feat(feat/sang/#29): 카테고리 드롭다운 메뉴 구현
  src/pages/products/index.html
  src/styles/layout/_header.scss
Labels: Feature

#38 modify(feat/ryu/#36): 메인 페이지 키보드 키로 동장 및 배너 크기 수정
  index.html
  src/styles/pages/_main.scss
Labels: BugFix, Modifiy

#40 fix(feat/kim/#34): 로그인, 회원가입 페이지 input 필드 레이아웃 무너짐 해결
  src/pages/login/index.html
  src/pages/register/index.html
  src/styles/pages/_login.scss
  src/styles/pages/_register.scss
Labels: BugFix

#46 modify(feat/kim/#41): 회원가입 페이지 체크박스 키보드 접근 가능하게 수정 및 scss 믹스인 사용
  src/pages/register/index.html
  src/styles/pages/_register.scss
Labels: Feature, Modifiy

#44 feat(feat/ryu/#32): 메인 페이지 팝업 완료
  index.html
  main.js
  src/styles/pages/_main.scss
Labels: Feature, Modifiy

#47 modify(feat/ryu/#45): 메인페이지 배너 스타일, 위치 수정
  index.html
  main.js
  src/styles/pages/_main.scss
Labels: Modifiy

#50 Feat/sang/#37: 헤더의 배송지 등록 기능 구현
  src/lib/components/header.js
  src/pages/address/index.html
  src/pages/address/index.js
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/layout/_header.scss
  src/styles/pages/_address.scss
  src/styles/pages/_index.scss
Labels: Feature

#52 feat(feat/ryu/#48): 메인페이지 상품 스와이퍼
  index.html
  main.js
  src/styles/components/_productCard.scss
  src/styles/pages/_main.scss
Labels: Feature

#53 feat(feat/kim/#49): 회원가입 페이지 이용약관 일괄 체크 기능 추가 및 로그인, 회원가입 헤더 영역 수정
  src/lib/components/checkbox.js
  src/lib/components/index.js
  src/pages/login/index.html
  src/pages/login/index.js
  src/pages/login/login.js
  src/pages/register/index.html
  src/pages/register/index.js
  src/pages/register/register.js
Labels: Feature

#42 feat(feat/kina/#39): 찜,알림버튼 toggle 구현
  public/images/product/Heart-grey.svg
  public/images/product/Heart-purple.svg
  public/images/product/bell-grey.svg
  public/images/product/bell-purple.svg
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature

#56 feat(feat/sang/#55): 장바구니 헤더 활성화 fixHeader에서 initHeader 로 변경
  src/pages/cart/index.html
  src/pages/cart/index.js
Labels: Feature

#58 Feat/sang/#51: 네비게이션 메뉴 펼치기, 체크박스 클릭 시 카운트 표시 및 초기화 기능 구현
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/pages/_products.scss
Labels: Feature

#60 Feat/kina/#43: 상품 주문 갯수 및 갯수에 따른 금액 계산 후 표시 기능
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature, a11y

#62 Feat/sang/#59: 네비게이션 체크박스 관련 기능 구현
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/layout/_header.scss
  src/styles/pages/_products.scss
Labels: BugFix, Feature

#63 feat(feat/ryu/#54): 장바구니 아이콘 클릭 시 장바구니 모달
  main.js
  src/lib/components/cartModal.js
  src/lib/components/index.js
  src/styles/components/_cartModal.scss
  src/styles/components/_index.scss
Labels: Feature

#65 feat(feat/kim/#57): 회원가입 페이지 필수 입력 필드 조건 문구 출력
  src/pages/register/index.html
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Feature

#69 feat(feat/kim/#66): 로그인 페이지 아이디, 비밀번호 조건 문구 출력 및 sr-only 레이블 추가
  src/pages/login/index.html
  src/pages/login/index.js
  src/styles/pages/_login.scss
Labels: Feature, a11y

#67 Feat/kina/#61 디테일페이지 네비게이션바 동작 구현
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: BugFix, Feature, Modifiy

#72 feat(feat/ryu/#64): 최근 본 상품
  index.html
  main.js
  src/lib/components/index.js
  src/lib/components/recentBar.js
  src/styles/components/_recentBar.scss
Labels: Feature

#73 Modify(feat/ryu/#64): 장바구니 아이콘에서의 문제 해결
  main.js
  src/lib/components/cartModal.js
  src/styles/components/_cartModal.scss
Labels: Modify

#75 Feat/sang/#71: 카테고리 목록 동적 렌더링
  src/pages/products/index.html
  src/pages/products/index.js
Labels: Feature

#76 feat(feat/kim/#70): 필수 입력란 입력 완료 및 필수 동의 체크란까지 모두 체크 완료 시 회원가입 버튼 활성화 기능 추가
  src/lib/components/checkbox.js
  src/pages/register/index.html
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Feature

#77 modify(feat/ryu/#74): 장바구니 페이지 마크업 및 스타일링 수정
  src/pages/cart/index.html
  src/styles/pages/_cart.scss
Labels: Modify

#80 fix(feat/kim/#78): changeAllCheck 모듈 레퍼런스 에러 해결
  src/lib/components/checkbox.js
  src/lib/components/index.js
  src/pages/register/index.js
Labels: BugFix

#82 fix(feat/kina/#79): main class명 수정
  src/pages/detail/index.html
  src/styles/pages/_detail.scss
Labels: BugFix

#85 feat(feat/kim/#84): 로그인 페이지 로그인 버튼 활성화 기능 및 회원가입 버튼 기능 추가
  src/lib/components/clickBtnMoveToSite.js
  src/lib/components/index.js
  src/lib/components/validationInput.js
  src/pages/login/index.html
  src/pages/login/index.js
  src/styles/pages/_login.scss
Labels: Feature

#87 Feat/sang/#81: 상품 카드 동적 렌더링 및 스켈레톤 UI 적용
  src/lib/components/index.js
  src/lib/components/productCard.js
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/components/_productCard.scss
  src/styles/pages/_products.scss
Labels: Feature

#92 feat(feat/kim/#86):회원가입 페이지 회원가입 기능 구현
  src/pages/register/index.html
  src/pages/register/index.js
Labels: Feature

#94 feat(feat/sang/#91): 카테고리 별 목록 나열 기능 구현
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/pages/_products.scss
Labels: Feature

#96 feat(feat/kim/#93): 로그인 기능 구현
  src/pages/login/index.html
  src/pages/login/index.js
Labels: Feature

#99 feat(feat/kina/#83): 디테일페이지 동적 렌더링
  src/lib/components/productCard.js
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature, Modify

#98 feat(feat/ryu/#88): 메인페이지 상품 리스트
  index.html
  main.js
  src/lib/components/cartModal.js
  src/lib/components/recentBar.js
  src/styles/components/_cartModal.scss
Labels: Feature, Refactor, Modify

#101 Feat/sang/#95: 장바구니 목록 데이터에서 받아와서 뿌리기
  src/pages/cart/index.html
  src/pages/cart/index.js
  src/styles/pages/_cart.scss
Labels: Feature, Modify

#102 Feat/kina/#100 디테일페이지 할인가격 표시 및 반영
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Modify

#106 Feat/sang/#103: 장바구니 체크박스 동작 및 확장 기능
  src/pages/cart/index.html
  src/pages/cart/index.js
  src/styles/pages/_cart.scss
Labels: Feature

#105 feat(feat/ryu/#104): 장바구니에 상품 담을 경우 데이터베이스로 이동
  src/lib/components/cartModal.js
Labels: Feature

#108 feat(feat/kim/#97): 회원가입 페이지 기능 추가
  src/lib/components/index.js
  src/lib/components/sliceNumberMaxLength.js
  src/lib/components/validationInput.js
  src/pages/register/index.html
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Feature, Modify

#113 Feat/sang/#107: 상품 수량 조절 및 가격 계산, 삭제 기능 및 스켈레톤 UI 적용
  src/lib/components/header.js
  src/pages/cart/index.html
  src/pages/cart/index.js
  src/styles/pages/_cart.scss
Labels: Feature

#111 Feat/kina/#110 설명부분 이미지 렌더링 및 교체
  public/images/product/Frame.png
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature, Modify

#115 Feat/sang/#114: 장바구니 페이지에서 배송지 저장/변경 및 주문 기능 구현
  public/images/product/cs-info.png
  public/images/product/ice-pack.png
  public/images/product/order-complete-check.svg
  public/images/product/styrofoam-box.png
  src/lib/components/address.js
  src/pages/cart/index.html
  src/pages/cart/index.js
  src/styles/pages/_cart.scss
Labels: Feature

#117 feat(feat/kim/#109): 회원가입 페이지 아이디, 이메일 중복 확인 체크 기능 추가
  src/pages/login/index.js
  src/pages/register/index.html
  src/pages/register/index.js
Labels: Feature

#120 Feat/sang/#116: 상품 분류 및 정렬 기능 구현
  src/pages/cart/index.html
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/pages/_products.scss
Labels: Feature

#124 modify(feat/kim/#122): 로그인, 이메일 중복확인 기능 보완 및 수정된 헤더 적용
  src/pages/login/index.html
  src/pages/register/index.html
  src/pages/register/index.js
Labels: Modify

#123 Feat/sang/#121: 상품목록 페이지의 페이지네이션 기능 및 장바구니 담기 기능
  src/lib/components/productCard.js
  src/pages/cart/index.js
  src/pages/products/index.html
  src/pages/products/index.js
  src/styles/layout/_header.scss
  src/styles/pages/_products.scss
Labels: Feature

#131 Modify(feat/ryu/#128): 상품 상세 페이지의 async/await 문제 및 장바구니 버블(팝업) 완료
  src/lib/components/cartModal.js
  src/pages/detail/index.html
  src/pages/detail/index.js
Labels: Modify

#133 feat(feat/kim/#125): 추가입력 사항(친구초대 추천인 아이디, 참여 이벤트명) 클릭 시 요소 추가
  src/pages/register/index.html
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Feature

#134 Feat/sang/#130: 디자인 디테일 작업 및 빌드 불가 문제 수정
  src/pages/cart/index.html
  src/pages/cart/index.js
  src/pages/login/index.js
  src/pages/mypage/index.js
  src/styles/layout/_header.scss
  src/styles/pages/_cart.scss
Labels: BugFix, Modify

#139 modify(feat/sang/#136): 헤더 최신화
  src/lib/components/header.js
  src/pages/address/index.html
  src/pages/cart/index.html
  src/pages/products/index.html
Labels: Modify

#140 feat(feat/kim/#137): 회원가입, 로그인, 마이 페이지 마크업 수정 및 회원탈퇴 기능 추가
  src/pages/login/index.html
  src/pages/mypage/index.html
  src/pages/mypage/index.js
  src/pages/register/index.html
Labels: Feature, Modify

#143 modify(feat/kim/#141): 회원가입 페이지 중복확인, 추천인 아이디 확인 기능 보완
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Modify

#146 Feat/kina/#127 후기 작성하기 및 보여주기 구현
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Feature, Modify

#148 feat(feat/kim/#144): 회원가입 페이지 인증번호 기능 구현
  src/pages/register/index.html
  src/pages/register/index.js
  src/styles/pages/_register.scss
Labels: Feature

#149 modify(feat/kina/#147): 제대로 보이지 않던 부분 수정
  src/pages/detail/index.html
  src/pages/detail/index.js
  src/styles/pages/_detail.scss
Labels: Modify

#151 modify(feat/sang/#150): 이미지 경로 배포 기준으로 표시가능하도록 수정
  src/pages/cart/index.js
  src/styles/components/_recentBar.scss
  src/styles/pages/_main.scss
Labels: Modify

#145 Feat/ryu/#138: 마이크로 애니메이션 및 이동 링크 추가
  index.html
  src/pages/benefit/index.html
  src/pages/benefit/index.js
  src/styles/components/_productCard.scss
  src/styles/components/_recentBar.scss
Labels: Feature, Modify

#155 modify(feat/sang/#154): 상품 디테일 페이지 헤더 수정
  src/pages/detail/index.html
Labels: Modify

#158 feat(feat/kina/#156): 경혜님 코드로 디테일페이지에서 장바구니 카운트 추가
  src/lib/components/cartModal.js
Labels: Feature

#160 modify(feat/sang/#159): span 태그 label로 변경, 기본 유저 데이터 세팅
  src/pages/mypage/index.html
  src/pages/mypage/index.js
  src/styles/pages/_mypage.scss
Labels: Modify
